stages:
  - prepare
  - lint
  - test
  - build
  - deploy

image: node:14

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - npm install

lint:
  stage: lint
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run lint

test:
  stage: test
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run test -- --coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

build:
  stage: build
  tags:
    - docker
  script:
    - export CI=
    - npm run build
  artifacts:
    paths:
      - ./build/

# deploy:
#   stage: deploy
#   dependencies:
#     - build
#   only:
#     - master
#   tags:
#     - deploy:helloworld
#   script:
#     - ./scripts/deploy.sh ./dist/
