import { createMuiTheme, withStyles } from '@material-ui/core/styles';

/**
 * Colors
 */

export const COLOR = {
  debug: 'rgba(0,0,0,0.1)',

  background: '#F0F1F6',

  primary: '#607D8B',
  primaryDark: '#455A64',
  accent: '#FFC107',
  inverse: '#FAFAFA',

  success: '#2ECC71',
  error: '#E74C3C',
  info: '#3498DB',
  warning: '#F1C40F',
  off: '#999999',

  text: '#040404',
  textSecondary: '#333333',

  textInverse: '#FAFAFA',
  textSecondaryInverse: '#CCCCCC',

  white: '#FFFFFF',
  black: '#000000',
};

export const THEME = createMuiTheme({
  palette: {
    primary: {
      main: COLOR.primary,
    },
    secondary: {
      main: COLOR.primaryDark,
    },
    error: {
      main: COLOR.error,
    },
    success: {
      main: COLOR.success,
    },
    info: {
      main: COLOR.info,
    },
    warning: {
      main: COLOR.warning,
    },
  },
});

export const CssVariables = withStyles((theme) => {
  const themePaletteType = theme.palette.type;
  const themeInversePaletteType = themePaletteType === 'dark' ? 'light' : 'dark';

  return {
    '@global': {
      ':root': {
        '--color-debug': COLOR.debug,
        '--color-background': COLOR.background,
        '--color-primary': COLOR.primary,
        '--color-primaryDark': COLOR.primaryDark,
        '--color-accent': COLOR.accent,
        '--color-inverse': COLOR.inverse,
        '--color-success': COLOR.success,
        '--color-error': COLOR.error,
        '--color-info': COLOR.info,
        '--color-warning': COLOR.warning,
        '--color-off': COLOR.off,
        '--color-text': COLOR.text,
        '--color-textSecondary': COLOR.textSecondary,
        '--color-textInverse': COLOR.textInverse,
        '--color-textSecondaryInverse': COLOR.textSecondaryInverse,
        '--color-white': COLOR.white,
        '--color-black': COLOR.black,
        '--theme-breakpoints-values-xs': `${theme.breakpoints.values.xs}px`,
        '--theme-breakpoints-values-sm': `${theme.breakpoints.values.sm}px`,
        '--theme-breakpoints-values-md': `${theme.breakpoints.values.md}px`,
        '--theme-breakpoints-values-lg': `${theme.breakpoints.values.lg}px`,
        '--theme-breakpoints-values-xl': `${theme.breakpoints.values.xl}px`,
        '--theme-direction': theme.direction,
        '--theme-gutters': `${theme.mixins.gutters().paddingLeft}px`,
        '--theme-toolbar-minHeight': `${theme.mixins.toolbar.minHeight}px`,
        '--theme-palette-common-black': theme.palette.common.black,
        '--theme-palette-common-white': theme.palette.common.white,
        '--theme-palette-primary-main': theme.palette.primary.main,
        '--theme-palette-primary-light': theme.palette.primary.light,
        '--theme-palette-primary-dark': theme.palette.primary.dark,
        '--theme-palette-primary-contrastText': theme.palette.primary.contrastText,
        '--theme-palette-secondary-main': theme.palette.secondary.main,
        '--theme-palette-secondary-light': theme.palette.secondary.light,
        '--theme-palette-secondary-dark': theme.palette.secondary.dark,
        '--theme-palette-secondary-contrastText': theme.palette.secondary.contrastText,
        '--theme-palette-error-main': theme.palette.error.main,
        '--theme-palette-error-light': theme.palette.error.light,
        '--theme-palette-error-dark': theme.palette.error.dark,
        '--theme-palette-error-contrastText': theme.palette.error.contrastText,
        '--theme-palette-warning-main': theme.palette.warning.main,
        '--theme-palette-warning-light': theme.palette.warning.light,
        '--theme-palette-warning-dark': theme.palette.warning.dark,
        '--theme-palette-warning-contrastText': theme.palette.warning.contrastText,
        '--theme-palette-info-main': theme.palette.info.main,
        '--theme-palette-info-light': theme.palette.info.light,
        '--theme-palette-info-dark': theme.palette.info.dark,
        '--theme-palette-info-contrastText': theme.palette.info.contrastText,
        '--theme-palette-success-main': theme.palette.success.main,
        '--theme-palette-success-light': theme.palette.success.light,
        '--theme-palette-success-dark': theme.palette.success.dark,
        '--theme-palette-success-contrastText': theme.palette.success.contrastText,
        '--theme-palette-grey-50': theme.palette.grey[50],
        '--theme-palette-grey-100': theme.palette.grey[100],
        '--theme-palette-grey-200': theme.palette.grey[200],
        '--theme-palette-grey-300': theme.palette.grey[300],
        '--theme-palette-grey-400': theme.palette.grey[400],
        '--theme-palette-grey-500': theme.palette.grey[500],
        '--theme-palette-grey-600': theme.palette.grey[600],
        '--theme-palette-grey-700': theme.palette.grey[700],
        '--theme-palette-grey-800': theme.palette.grey[800],
        '--theme-palette-grey-900': theme.palette.grey[900],
        '--theme-palette-grey-A100': theme.palette.grey.A100,
        '--theme-palette-grey-A200': theme.palette.grey.A200,
        '--theme-palette-grey-A400': theme.palette.grey.A400,
        '--theme-palette-grey-A700': theme.palette.grey.A700,
        '--theme-palette-text-primary': theme.palette.text.primary,
        '--theme-palette-text-secondary': theme.palette.text.secondary,
        '--theme-palette-text-disabled': theme.palette.text.disabled,
        '--theme-palette-text-hint': theme.palette.text.hint,
        '--theme-palette-divider': theme.palette.divider,
        '--theme-palette-background-paper': theme.palette.background.paper,
        '--theme-palette-background-default': theme.palette.background.default,
        '--theme-palette-action-active': theme.palette.action.active,
        '--theme-palette-action-hover': theme.palette.action.hover,
        '--theme-palette-action-hoverOpacity': theme.palette.action.hoverOpacity,
        '--theme-palette-action-selected': theme.palette.action.selected,
        '--theme-palette-action-selectedOpacity': theme.palette.action.selectedOpacity,
        '--theme-palette-action-disabled': theme.palette.action.disabled,
        '--theme-palette-action-disabledBackground': theme.palette.action.disabledBackground,
        '--theme-palette-action-disabledOpacity': theme.palette.action.disabledOpacity,
        '--theme-palette-action-focus': theme.palette.action.focus,
        '--theme-palette-action-focusOpacity': theme.palette.action.focusOpacity,
        '--theme-palette-action-activatedOpacity': theme.palette.action.activatedOpacity,
        '--theme-shadows-0': theme.shadows[0],
        '--theme-shadows-1': theme.shadows[1],
        '--theme-shadows-2': theme.shadows[2],
        '--theme-shadows-3': theme.shadows[3],
        '--theme-shadows-4': theme.shadows[4],
        '--theme-shadows-5': theme.shadows[5],
        '--theme-shadows-6': theme.shadows[6],
        '--theme-shadows-7': theme.shadows[7],
        '--theme-shadows-8': theme.shadows[8],
        '--theme-shadows-9': theme.shadows[9],
        '--theme-shadows-10': theme.shadows[10],
        '--theme-shadows-11': theme.shadows[11],
        '--theme-shadows-12': theme.shadows[12],
        '--theme-shadows-13': theme.shadows[13],
        '--theme-shadows-14': theme.shadows[14],
        '--theme-shadows-15': theme.shadows[15],
        '--theme-shadows-16': theme.shadows[16],
        '--theme-shadows-17': theme.shadows[17],
        '--theme-shadows-18': theme.shadows[18],
        '--theme-shadows-19': theme.shadows[19],
        '--theme-shadows-20': theme.shadows[20],
        '--theme-shadows-21': theme.shadows[21],
        '--theme-shadows-22': theme.shadows[22],
        '--theme-shadows-23': theme.shadows[23],
        '--theme-shadows-24': theme.shadows[24],
        '--theme-typography-htmlFontSize': `${theme.typography.htmlFontSize}px`,
        '--theme-typography-fontFamily': theme.typography.fontFamily,
        '--theme-typography-fontSize': `${theme.typography.fontSize}px`,
        '--theme-typography-fontWeightLight': theme.typography.fontWeightLight,
        '--theme-typography-fontWeightRegular': theme.typography.fontWeightRegular,
        '--theme-typography-fontWeightMedium': theme.typography.fontWeightMedium,
        '--theme-typography-fontWeightBold': theme.typography.fontWeightBold,
        '--theme-typography-h1-fontFamily': theme.typography.h1.fontFamily,
        '--theme-typography-h1-fontWeight': theme.typography.h1.fontWeight,
        '--theme-typography-h1-fontSize': theme.typography.h1.fontSize,
        '--theme-typography-h1-lineHeight': theme.typography.h1.lineHeight,
        '--theme-typography-h1-letterSpacing': theme.typography.h1.letterSpacing,
        '--theme-typography-h2-fontFamily': theme.typography.h2.fontFamily,
        '--theme-typography-h2-fontWeight': theme.typography.h2.fontWeight,
        '--theme-typography-h2-fontSize': theme.typography.h2.fontSize,
        '--theme-typography-h2-lineHeight': theme.typography.h2.lineHeight,
        '--theme-typography-h2-letterSpacing': theme.typography.h2.letterSpacing,
        '--theme-typography-h3-fontFamily': theme.typography.h3.fontFamily,
        '--theme-typography-h3-fontWeight': theme.typography.h3.fontWeight,
        '--theme-typography-h3-fontSize': theme.typography.h3.fontSize,
        '--theme-typography-h3-lineHeight': theme.typography.h3.lineHeight,
        '--theme-typography-h3-letterSpacing': theme.typography.h3.letterSpacing,
        '--theme-typography-h4-fontFamily': theme.typography.h4.fontFamily,
        '--theme-typography-h4-fontWeight': theme.typography.h4.fontWeight,
        '--theme-typography-h4-fontSize': theme.typography.h4.fontSize,
        '--theme-typography-h4-lineHeight': theme.typography.h4.lineHeight,
        '--theme-typography-h4-letterSpacing': theme.typography.h4.letterSpacing,
        '--theme-typography-h5-fontFamily': theme.typography.h5.fontFamily,
        '--theme-typography-h5-fontWeight': theme.typography.h5.fontWeight,
        '--theme-typography-h5-fontSize': theme.typography.h5.fontSize,
        '--theme-typography-h5-lineHeight': theme.typography.h5.lineHeight,
        '--theme-typography-h5-letterSpacing': theme.typography.h5.letterSpacing,
        '--theme-typography-h6-fontFamily': theme.typography.h6.fontFamily,
        '--theme-typography-h6-fontWeight': theme.typography.h6.fontWeight,
        '--theme-typography-h6-fontSize': theme.typography.h6.fontSize,
        '--theme-typography-h6-lineHeight': theme.typography.h6.lineHeight,
        '--theme-typography-h6-letterSpacing': theme.typography.h6.letterSpacing,
        '--theme-typography-subtitle1-fontFamily': theme.typography.subtitle1.fontFamily,
        '--theme-typography-subtitle1-fontWeight': theme.typography.subtitle1.fontWeight,
        '--theme-typography-subtitle1-fontSize': theme.typography.subtitle1.fontSize,
        '--theme-typography-subtitle1-lineHeight': theme.typography.subtitle1.lineHeight,
        '--theme-typography-subtitle1-letterSpacing': theme.typography.subtitle1.letterSpacing,
        '--theme-typography-subtitle2-fontFamily': theme.typography.subtitle2.fontFamily,
        '--theme-typography-subtitle2-fontWeight': theme.typography.subtitle2.fontWeight,
        '--theme-typography-subtitle2-fontSize': theme.typography.subtitle2.fontSize,
        '--theme-typography-subtitle2-lineHeight': theme.typography.subtitle2.lineHeight,
        '--theme-typography-subtitle2-letterSpacing': theme.typography.subtitle2.letterSpacing,
        '--theme-typography-body1-fontFamily': theme.typography.body1.fontFamily,
        '--theme-typography-body1-fontWeight': theme.typography.body1.fontWeight,
        '--theme-typography-body1-fontSize': theme.typography.body1.fontSize,
        '--theme-typography-body1-lineHeight': theme.typography.body1.lineHeight,
        '--theme-typography-body1-letterSpacing': theme.typography.body1.letterSpacing,
        '--theme-typography-body2-fontFamily': theme.typography.body2.fontFamily,
        '--theme-typography-body2-fontWeight': theme.typography.body2.fontWeight,
        '--theme-typography-body2-fontSize': theme.typography.body2.fontSize,
        '--theme-typography-body2-lineHeight': theme.typography.body2.lineHeight,
        '--theme-typography-body2-letterSpacing': theme.typography.body2.letterSpacing,
        '--theme-typography-button-fontFamily': theme.typography.button.fontFamily,
        '--theme-typography-button-fontWeight': theme.typography.button.fontWeight,
        '--theme-typography-button-fontSize': theme.typography.button.fontSize,
        '--theme-typography-button-lineHeight': theme.typography.button.lineHeight,
        '--theme-typography-button-letterSpacing': theme.typography.button.letterSpacing,
        '--theme-typography-button-textTransform': theme.typography.button.textTransform,
        '--theme-typography-caption-fontFamily': theme.typography.caption.fontFamily,
        '--theme-typography-caption-fontWeight': theme.typography.caption.fontWeight,
        '--theme-typography-caption-fontSize': theme.typography.caption.fontSize,
        '--theme-typography-caption-lineHeight': theme.typography.caption.lineHeight,
        '--theme-typography-caption-letterSpacing': theme.typography.caption.letterSpacing,
        '--theme-typography-overline-fontFamily': theme.typography.overline.fontFamily,
        '--theme-typography-overline-fontWeight': theme.typography.overline.fontWeight,
        '--theme-typography-overline-fontSize': theme.typography.overline.fontSize,
        '--theme-typography-overline-lineHeight': theme.typography.overline.lineHeight,
        '--theme-typography-overline-letterSpacing': theme.typography.overline.letterSpacing,
        '--theme-typography-overline-textTransform': theme.typography.overline.textTransform,
        '--theme-spacing': theme.spacing(),
        '--theme-spacing-1': `${theme.spacing(1)}px`,
        '--theme-spacing-2': `${theme.spacing(2)}px`,
        '--theme-spacing-3': `${theme.spacing(3)}px`,
        '--theme-spacing-4': `${theme.spacing(4)}px`,
        '--theme-shape-borderRadius': `${theme.shape.borderRadius}px`,
        '--theme-transitions-easing-easeInOut': theme.transitions.easing.easeInOut,
        '--theme-transitions-easing-easeOut': theme.transitions.easing.easeOut,
        '--theme-transitions-easing-easeIn': theme.transitions.easing.easeIn,
        '--theme-transitions-easing-sharp': theme.transitions.easing.sharp,
        '--theme-transitions-duration-shortest': theme.transitions.duration.shortest,
        '--theme-transitions-duration-shorter': theme.transitions.duration.shorter,
        '--theme-transitions-duration-short': theme.transitions.duration.short,
        '--theme-transitions-duration-standard': theme.transitions.duration.standard,
        '--theme-transitions-duration-complex': theme.transitions.duration.complex,
        '--theme-transitions-duration-enteringScreen': theme.transitions.duration.enteringScreen,
        '--theme-transitions-duration-leavingScreen': theme.transitions.duration.leavingScreen,
        '--theme-zIndex-mobileStepper': theme.zIndex.mobileStepper,
        '--theme-zIndex-speedDial': theme.zIndex.speedDial,
        '--theme-zIndex-appBar': theme.zIndex.appBar,
        '--theme-zIndex-drawer': theme.zIndex.drawer,
        '--theme-zIndex-modal': theme.zIndex.modal,
        '--theme-zIndex-snackbar': theme.zIndex.snackbar,
        '--theme-zIndex-tooltip': theme.zIndex.tooltip,
        [`${theme.breakpoints.up('xs')} and (orientation: landscape)`]: {
          '--theme-toolbar-minHeight': `${
            theme.mixins.toolbar[`${theme.breakpoints.up('xs')} and (orientation: landscape)`].minHeight
          }px`,
        },
        [theme.breakpoints.up('sm')]: {
          '--theme-gutters': `${theme.mixins.gutters()[theme.breakpoints.up('sm')].paddingLeft}px`,
          '--theme-toolbar-minHeight': `${theme.mixins.toolbar[theme.breakpoints.up('sm')].minHeight}px`,
        },
        // custom
        '--theme-palette-primary-type': theme.palette.primary[themePaletteType],
        '--theme-palette-primary-type-inverse': theme.palette.primary[themeInversePaletteType],
        '--theme-palette-secondary-type': theme.palette.secondary[themePaletteType],
        '--theme-palette-secondary-type-inverse': theme.palette.secondary[themeInversePaletteType],
        '--theme-palette-error-type': theme.palette.error[themePaletteType],
        '--theme-palette-error-type-inverse': theme.palette.error[themeInversePaletteType],
        '--theme-palette-warning-type': theme.palette.warning[themePaletteType],
        '--theme-palette-warning-type-inverse': theme.palette.warning[themeInversePaletteType],
        '--theme-palette-info-type': theme.palette.info[themePaletteType],
        '--theme-palette-info-type-inverse': theme.palette.info[themeInversePaletteType],
        '--theme-palette-success-type': theme.palette.success[themePaletteType],
        '--theme-palette-success-type-inverse': theme.palette.success[themeInversePaletteType],
      },
    },
  };
})(function CssVariables() {
  return null;
});
